For each of the following questions, formulate a null and alternative hypothesis (be as specific as you can be), then give an example of what a true positive, true negative, type I and type II errors would look like. Note that some of the questions are intentionally phrased in a vague way. It is your job to reword these as more precise questions that could be tested.

* Has the network latency gone up since we switched internet service providers?
* Is the website redesign any good?
* Is our television ad driving more sales?

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from math import sqrt

from pydataset import data
from scipy import stats

In [2]:
# Null Hypothesis: The network letency has not gone up since we switched ISPs
# Alternate Hypothesis: The network letency has gone up since we switched ISPs

# True Positive: Latency was measured and it did go up from 50ms to 100ms
# True Negative: Latency was measured and it did not go up. It was measured at 50ms before the switch and has remained at 50ms.

# False Positive (Type I): The latency seems to have gone up but has not gone up.
# False Negative (Type II): The latency does no seem to have gone up but actually has.

In [3]:
# Null Hypothesis: The website redesign is not any good.
# Alternate Hypothesis:  The website redesign is good.

# True Positive: The website redesign is actually good. Customer feedback shows more positive responses to it than the old one.
# True Negative: The website redesign is actually not good. Customer feedback shows more negative responses to it than the old one.

# False Positive (Type I): The website redesign appears to be good but actually has many hidden bugs and errors and other issues.
# False Negative (Type II): The website redesign appears to be bad, but in fact runs much smoother and functions better.

In [4]:
# Null Hypothesis: Our television ad is not driving more sales.
# Alternate Hypothesis: Our television ad is driving more sales.

# True Positive: The television ads have brought more customers into the store after they watched the ad.
# True Negative:  The television ads have nor brought more customers into the store after they watched the ad.

# False Positive (Type I): There was an increase in sales, but this was due to regular sales fluctuations and not increased sales 
# caused by the ad. Without the ad sales would have still increased.
# False Negative (Type II): There was no increase in sales, but this was due to regular sales fluctuations being lower, causing a 
# percieved lack of change in sales. Without the ad, sales would have been even lower.

# Comparison of Groups Exercises

1. Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.

                    Codeup Student	  Not Codeup Student
Uses a Macbook	         49                 20
Doesn't Use A Macbook	  1	                30

In [5]:
mac = pd.DataFrame([[49,20],[1,30]],columns = ['CodeUp_Student','Not_Codeup_Student']) # Create data frame with information
mac

CodeUp_Student  Not_Codeup_Student
0              49                  20
1               1                  30

In [6]:
chi, p, degf, exp = stats.chi2_contingency(mac)
chi, p, degf, exp

(36.65264142122487,
 1.4116760526193828e-09,
 1,
 array([[34.5, 34.5],
        [15.5, 15.5]]))

In [7]:
# There is a very strong correlation between using a Mac and being a CodeUp student.
# I believe that using a mac is dependent on being a CodeUp student

2, Choose another 2 categorical variables from the mpg dataset.

* State your null and alternative hypotheses.
* State your alpha.
* Perform a chi^2 test of independence.
* State your conclusion

In [8]:
mpg = data('mpg')
mpg.head(3)

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact

In [9]:
mpg['age'] = pd.qcut(mpg.year,2,labels=['old','new'])
mpg.head(3)

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class  \
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact   
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact   
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact   

   age  
1  old  
2  old  
3  new

In [10]:
mpg['avg_mpg'] = (mpg.hwy + mpg.cty)/2
mpg.head(3)

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class  \
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact   
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact   
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact   

   age  avg_mpg  
1  old     23.5  
2  old     25.0  
3  new     25.5

In [11]:
mpg['mpg_cat'] = pd.qcut(mpg.avg_mpg,2,labels = ['low_mpg','high_mpg'])
mpg.head(3)

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class  \
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact   
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact   
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact   

   age  avg_mpg   mpg_cat  
1  old     23.5  high_mpg  
2  old     25.0  high_mpg  
3  new     25.5  high_mpg

In [12]:
age_mpg = pd.crosstab(mpg.age,mpg.mpg_cat)
age_mpg

mpg_cat  low_mpg  high_mpg
age                       
old           57        60
new           64        53

In [13]:
# Null : There is no correlation between car age and average gas mileage
# Alternate : There is a correlatino between car age and average gas mileage

alpha = 0.10

chi, p, degf, exp = stats.chi2_contingency(age_mpg)
chi, p, degf, exp

(0.6161047319534849,
 0.4324984858656389,
 1,
 array([[60.5, 56.5],
        [60.5, 56.5]]))

In [14]:
if p < alpha:
    print('There is a correlation between car age and average gas mileage.')
else:
    print('There is no correlation between car age and average gas mileage.')

There is no correlation between car age and average gas mileage.


3. Use the data from the employees database to answer these questions:

* Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)
* Is an employee's gender independent of whether or not they are or have been a manager?

In [15]:
import env
from sqlalchemy import text, create_engine

url = env.get_connection('employees')
engine = create_engine(url)
sal = text('''
        SELECT * FROM employees as E
        JOIN dept_emp as DE USING(emp_no)
        JOIN departments as D USING(dept_no)
        WHERE to_date > CURDATE()
        ''')
s = pd.read_sql(sal,engine.connect())
s

dept_no  emp_no  birth_date first_name    last_name gender   hire_date  \
0         d009   10038  1960-07-20       Huan        Lortz      M  1989-09-20   
1         d009   10049  1961-04-24      Basil       Tramer      F  1992-05-04   
2         d009   10060  1961-10-15   Breannda  Billingsley      M  1987-11-02   
3         d009   10088  1954-02-25   Jungsoon     Syrzycki      F  1988-09-02   
4         d009   10112  1963-08-13   Yuichiro        Swick      F  1985-10-08   
...        ...     ...         ...        ...          ...    ...         ...   
240119    d007  499966  1955-12-04    Mihalis     Crabtree      F  1985-06-13   
240120    d007  499976  1963-08-20   Guozhong       Felder      M  1988-12-26   
240121    d007  499980  1959-06-28       Gino        Usery      M  1991-02-11   
240122    d007  499986  1952-07-22     Nathan        Ranta      F  1985-08-11   
240123    d007  499987  1961-09-05      Rimli       Dusink      F  1998-09-20   

         from_date     to_date         dept_name  
0       1989-09-20  9999-01-01  Customer Service  
1       1992-05-04  9999-01-01  Customer Service  
2       1992-11-11  9999-01-01  Customer Service  
3       1992-03-21  9999-01-01  Customer Service  
4       1998-05-01  9999-01-01  Customer Service  
...            ...         ...               ...  
240119  1985-06-13  9999-01-01             Sales  
240120  1988-12-26  9999-01-01             Sales  
240121  1991-02-11  9999-01-01             Sales  
240122  1985-08-11  9999-01-01             Sales  
240123  1999-12-21  9999-01-01             Sales  

[240124 rows x 10 columns]

In [16]:
smg = s[(s.dept_name == 'Sales') | (s.dept_name == 'Marketing')]
smg.head()

dept_no  emp_no  birth_date first_name  last_name gender   hire_date  \
104290    d001   10017  1958-07-06  Cristinel  Bouloucos      F  1993-08-03   
104291    d001   10058  1954-10-01    Berhard   McFarlin      M  1987-04-13   
104292    d001   10140  1957-03-11      Yucel      Auria      F  1991-03-14   
104293    d001   10228  1953-04-21   Karoline   Cesareni      F  1991-08-26   
104294    d001   10239  1955-03-31   Nikolaos      Llado      F  1995-05-08   

         from_date     to_date  dept_name  
104290  1993-08-03  9999-01-01  Marketing  
104291  1988-04-25  9999-01-01  Marketing  
104292  1991-03-14  9999-01-01  Marketing  
104293  1993-01-28  9999-01-01  Marketing  
104294  1996-05-04  9999-01-01  Marketing

In [17]:
smg_ct = pd.crosstab(smg.gender,smg.dept_name)
smg_ct

dept_name  Marketing  Sales
gender                     
F               5864  14999
M               8978  22702

In [18]:
chi, p, degf, exp = stats.chi2_contingency(smg_ct)
chi, p, degf, exp

(0.3240332004060638,
 0.5691938610810126,
 1,
 array([[ 5893.2426013, 14969.7573987],
        [ 8948.7573987, 22731.2426013]]))

In [19]:
if p < alpha:
    print('There is a correlation between gender and working on sales or marketing.')
else:
    print('There is no correlation between gender and working on sales or marketing.')

There is no correlation between gender and working on sales or marketing.


In [20]:
manager = text('''
        SELECT * FROM dept_manager as DM
        RIGHT JOIN employees as E USING(emp_no)
        ''')
mng = pd.read_sql(manager,engine.connect())
mng

emp_no  birth_date first_name last_name gender   hire_date dept_no  \
0        10001  1953-09-02     Georgi   Facello      M  1986-06-26    None   
1        10002  1964-06-02    Bezalel    Simmel      F  1985-11-21    None   
2        10003  1959-12-03      Parto   Bamford      M  1986-08-28    None   
3        10004  1954-05-01  Chirstian   Koblick      M  1986-12-01    None   
4        10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12    None   
...        ...         ...        ...       ...    ...         ...     ...   
300019  499995  1958-09-24     Dekang  Lichtner      F  1993-01-12    None   
300020  499996  1953-03-07       Zito      Baaz      M  1990-09-27    None   
300021  499997  1961-08-03    Berhard    Lenart      M  1986-04-21    None   
300022  499998  1956-09-05   Patricia   Breugel      M  1993-10-13    None   
300023  499999  1958-05-01     Sachin   Tsukuda      M  1997-11-30    None   

       from_date to_date  
0           None    None  
1           None    None  
2           None    None  
3           None    None  
4           None    None  
...          ...     ...  
300019      None    None  
300020      None    None  
300021      None    None  
300022      None    None  
300023      None    None  

[300024 rows x 9 columns]

In [21]:
mng['manager'] = np.where(mng.dept_no.isnull(),'No','Yes')
mng.manager.value_counts()

No     300000
Yes        24
Name: manager, dtype: int64

In [22]:
mng.head()

emp_no  birth_date first_name last_name gender   hire_date dept_no  \
0   10001  1953-09-02     Georgi   Facello      M  1986-06-26    None   
1   10002  1964-06-02    Bezalel    Simmel      F  1985-11-21    None   
2   10003  1959-12-03      Parto   Bamford      M  1986-08-28    None   
3   10004  1954-05-01  Chirstian   Koblick      M  1986-12-01    None   
4   10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12    None   

  from_date to_date manager  
0      None    None      No  
1      None    None      No  
2      None    None      No  
3      None    None      No  
4      None    None      No

In [23]:
m = pd.crosstab(mng.gender,mng.manager)
m

manager      No  Yes
gender              
F        120038   13
M        179962   11

In [24]:
chi, p, degf, exp = stats.chi2_contingency(m)
chi, p, degf, exp

(1.4566857643547197,
 0.22745818732810363,
 1,
 array([[1.20041397e+05, 9.60331174e+00],
        [1.79958603e+05, 1.43966883e+01]]))

In [25]:
if p < alpha:
    print('There is a correlation between gender and being a manager.')
else:
    print('There is no correlation between gender and being a manager.')

There is no correlation between gender and being a manager.


# Correlation Exercises

1. Answer with the type of stats test you would use (assume normal distribution):

* Is there a relationship between the length of your arm and the length of your foot?
* Does smoking affect when or not someone has lung cancer?
* Is gender independent of a person’s blood type?
* Does whether or not a person has a cat or dog affect whether they live in an apartment?
* Does the length of time of the lecture correlate with a student's grade?


2. Use the telco_churn data.

* Does tenure correlate with monthly charges?
* Total charges?
* What happens if you control for phone and internet service?

In [26]:
url = env.get_connection('telco_churn')
engine = create_engine(url)
xx = text('''
        SHOW TABLES
        ''')
telco = pd.read_sql(xx,engine.connect())
telco

Tables_in_telco_churn
0          contract_types
1          customer_churn
2      customer_contracts
3        customer_details
4       customer_payments
5        customer_signups
6  customer_subscriptions
7               customers
8  internet_service_types
9           payment_types

3. Use the employees database.
* Is there a relationship between how long an employee has been with the company and their salary?
* Is there a relationship between how long an employee has been with the company and the number of titles they have had?

In [27]:
url = env.get_connection('employees')
engine = create_engine(url)
xx = text('''
        SHOW TABLES
        ''')
emp = pd.read_sql(xx,engine.connect())
emp

Tables_in_employees
0         departments
1            dept_emp
2        dept_manager
3           employees
4            salaries
5              titles

4. Use the sleepstudy data.
* Is there a relationship between days and reaction time?